package forms;

import bo.GestorChat;
import objetos.Usuario;
import bo.GestorUsuario;
import interfaces.IGestorChats;
import interfaces.IGestorUsuario;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import objetos.Chat;
import org.bson.types.ObjectId;

/**
 *
 * @author Pedro
 */
public class EditarChat extends javax.swing.JFrame {

    Usuario us;
    Chat chat;
    IGestorUsuario gu;
    IGestorChats gc;

    /**
     * Creates new form NuevoChat
     *
     * @param us
     * @param chat
     */
    public EditarChat(Usuario us, Chat chat) {
        initComponents();
        this.us = us;
        this.chat = chat;
        this.gu = new GestorUsuario();
        this.gc = new GestorChat();
    }

    public boolean validarTitulo() {
        if (this.txt_titulo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Llene el campo titulo",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }

        return true;
    }

    public boolean validarContacto() {
        if (this.txt_contacto.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Llene el campo Contacto",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
        if (!this.txt_contacto.getText().matches("^[0-9]{10}$")) {
            JOptionPane.showMessageDialog(null, "Teléfono solo acepta numeros de 10 caracteres",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    public boolean agregarParticipante() throws Exception {

        ObjectId con = gu.buscar(this.txt_contacto.getText());
        if (con == null) {
            JOptionPane.showMessageDialog(null, "Contacto no existe",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        } else {
            List<ObjectId> part = chat.getIntegrantes();
            part.add(con);
            chat.setIntegrantes(part);

            gc.editarChat(chat);

            JOptionPane.showMessageDialog(null, "Integrante Agregado",
                    "Aviso", JOptionPane.INFORMATION_MESSAGE);
            return true;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btn_editarTitulo = new javax.swing.JButton();
        txt_contacto = new javax.swing.JTextField();
        txt_titulo = new javax.swing.JTextField();
        btn_agregarCon = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chat Nuevo");

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Pedro\\Documents\\GitHub\\juatsapp\\juatsapp_Presentacion\\src\\main\\java\\recursos\\logo (1).png")); // NOI18N

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Contacto");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Titulo ");

        jButton1.setBackground(new java.awt.Color(153, 0, 51));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btn_editarTitulo.setBackground(new java.awt.Color(102, 153, 255));
        btn_editarTitulo.setForeground(new java.awt.Color(0, 0, 0));
        btn_editarTitulo.setText("Editar Titulo");
        btn_editarTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarTituloActionPerformed(evt);
            }
        });

        btn_agregarCon.setBackground(new java.awt.Color(102, 153, 255));
        btn_agregarCon.setForeground(new java.awt.Color(0, 0, 0));
        btn_agregarCon.setText("Agregar Contacto");
        btn_agregarCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarConActionPerformed(evt);
            }
        });

        btn_eliminar.setBackground(new java.awt.Color(102, 153, 255));
        btn_eliminar.setForeground(new java.awt.Color(0, 0, 0));
        btn_eliminar.setText("Eliminar Chat");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(358, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(33, 33, 33)
                                        .addComponent(txt_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btn_agregarCon)
                                            .addComponent(txt_contacto))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btn_editarTitulo)
                                .addGap(82, 82, 82))))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btn_eliminar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addComponent(btn_editarTitulo)
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_contacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btn_agregarCon)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_eliminar)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Mensajes msj = new Mensajes(us, chat);
            msj.setVisible(true);
            dispose();
        } catch (Exception ex) {
            Logger.getLogger(EditarChat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_editarTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarTituloActionPerformed
        try {
            if (validarTitulo()) {
                this.chat.setTituloChat(this.txt_titulo.getText());
                gc.editarChat(chat);
                JOptionPane.showMessageDialog(null, "Titulo editado",
                    "Aviso", JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (Exception ex) {
            Logger.getLogger(EditarChat.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Chat no editado",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_editarTituloActionPerformed

    private void btn_agregarConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarConActionPerformed
        try {
            if (validarContacto()) {
                agregarParticipante();
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_agregarConActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        try {
            // TODO add your handling code here:
            if(gc.eliminarChat(chat)){
                JOptionPane.showMessageDialog(null, "Chat eliminado",
                    "Aviso", JOptionPane.INFORMATION_MESSAGE);
                Chats c = new Chats(us);
                c.setVisible(true);
                dispose();
            }
        } catch (Exception ex) {
            Logger.getLogger(EditarChat.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Chat no eliminado",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_eliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregarCon;
    private javax.swing.JButton btn_editarTitulo;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_contacto;
    private javax.swing.JTextField txt_titulo;
    // End of variables declaration//GEN-END:variables
}
