/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import bo.GestorChat;
import interfaces.IGestorChats;
import javax.swing.*;
import java.awt.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import objetos.Chat;
import objetos.Mensaje;
import objetos.Usuario;

/**
 *
 * @author Pedro
 */
public class Mensajes extends javax.swing.JFrame {

    private JList<String> messageList = null;
    private DefaultListModel<String> listModel;
//    private final DefaultListModel<String> messageListModel;
    private Usuario us;
    private Chat chat;
    private IGestorChats gc;
    private Timer timer;

    /**
     * Creates new form Chats
     *
     * @param us
     * @param chat
     * @throws java.lang.Exception
     */
    public Mensajes(Usuario us, Chat chat) throws Exception {
        initComponents();
        this.us = us;
        this.chat = chat;
        this.lbl_titulo.setText(chat.getTituloChat());
        this.gc = new GestorChat();

        jPanel1.setLayout(new BorderLayout());
        this.jPanel1.setPreferredSize(new Dimension(200, 250));
        // Inicializa el modelo de la lista de mensajes
//        messageListModel = new DefaultListModel<>();
        
        
        
        int delay = 1000; // 5000 milisegundos = 5 segundos
        timer = new Timer(delay, e -> {
            try {
                listModel = new DefaultListModel<>();
                for (Mensaje mensaje : gc.buscarMensajesChat(chat)) {
                    listModel.addElement(mensaje.toString());
                }
                
                // Inicializa la lista de mensajes
                messageList = new JList<>(listModel);
                
                // Agrega la lista de mensajes a un JScrollPane para permitir desplazamiento
                JScrollPane scrollPane = new JScrollPane(messageList);
                this.jPanel1.add(scrollPane, BorderLayout.CENTER);
            } catch (Exception ex) {
                Logger.getLogger(Mensajes.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
        timer.start();

        System.out.println(chat.getTituloChat());

    }

    public void addMessage() throws Exception {
        // Obtiene la fecha y hora actual
        Date date = new Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
        String formattedDate = dateFormat.format(date);

        Mensaje msj = new Mensaje();
        msj.setFechaHora(date);
        msj.setMensaje(this.txt_mensaje.getText());
        msj.setTelefono(us.getTelefono());
        msj.setAutor(us.getId());

        // Construye el mensaje con la fecha, autor y texto del mensaje
//        String formattedMessage = "[" + formattedDate + "] " + us.getTelefono() + ": " + msj.getMensaje();

        // Agrega el mensaje al modelo de la lista
        listModel.addElement(msj.toString());
        if (!gc.agregarMsj(msj, chat)) {
            JOptionPane.showMessageDialog(null, "Error al agregar mensaje a la base de datos",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }

        System.out.println("Enviar");
    }

    public static void main(String args[]) {
        // Crea y muestra el formulario
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    Chat c = new Chat();
                    Usuario u = new Usuario();
                    new Mensajes(u, c).setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(Mensajes.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_p = new javax.swing.JPanel();
        btn_enviar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_mensaje = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbl_titulo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btn_regresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jp_p.setBackground(new java.awt.Color(102, 153, 255));

        btn_enviar.setBackground(new java.awt.Color(102, 153, 255));
        btn_enviar.setForeground(new java.awt.Color(0, 0, 0));
        btn_enviar.setText("Enviar");
        btn_enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enviarActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Pedro\\Documents\\GitHub\\juatsapp\\juatsapp_Presentacion\\src\\main\\java\\recursos\\logo (1).png")); // NOI18N

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Chat");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 248, Short.MAX_VALUE)
        );

        lbl_titulo.setForeground(new java.awt.Color(0, 0, 0));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btn_regresar.setBackground(new java.awt.Color(204, 0, 0));
        btn_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_pLayout = new javax.swing.GroupLayout(jp_p);
        jp_p.setLayout(jp_pLayout);
        jp_pLayout.setHorizontalGroup(
            jp_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_pLayout.createSequentialGroup()
                .addGroup(jp_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_pLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jp_pLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jp_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_titulo)
                            .addComponent(jButton1)
                            .addGroup(jp_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btn_regresar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jp_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jp_pLayout.createSequentialGroup()
                        .addComponent(txt_mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_enviar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );
        jp_pLayout.setVerticalGroup(
            jp_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_pLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_pLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jp_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_enviar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jp_pLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_titulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(31, 31, 31))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_p, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_p, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enviarActionPerformed
        try {
            this.addMessage();
            
        } catch (Exception ex) {
            Logger.getLogger(Mensajes.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.jPanel1.repaint();
    }//GEN-LAST:event_btn_enviarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            gc.buscarMensajesChat(this.chat);
        } catch (Exception ex) {
            Logger.getLogger(Mensajes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regresarActionPerformed
        try {
            // TODO add your handling code here:
            Chats m = new Chats(us);
            m.setVisible(true);
            dispose();
        } catch (Exception ex) {
            Logger.getLogger(Mensajes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_regresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_enviar;
    private javax.swing.JButton btn_regresar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jp_p;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JTextField txt_mensaje;
    // End of variables declaration//GEN-END:variables
}
